apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
data:
  policy.csv: |
    g, superuser, role:admin
    g, backstage, role:readonly
  policy.default: ""
  policy.matchMode: glob
  scopes: '[groups]'
